service: telegram-lambda-bot

frameworkVersion: "4.17.1"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

plugins:
  - serverless-offline

functions:
  getData:
    handler: dist/bots/Telegram/TelegramLambdaHandler.lambdaFunction
    events:
      - http:
          path: telegram
          method: post
    package:
      include:
        - dist/bots/Telegram/**
      exclude:
        - dist/**/*.map

build:
  esbuild:
    bundle: false
    minify: false
    sourcemap: true
    target: node18
    platform: node
    format: esm
