name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Run tests
        run: npx vitest run
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: production

      - name: Build project
        run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: production
